name: Build and push Docker images

on:
  workflow_dispatch:
  schedule:
  - cron: '16 11 * * *'

env:
  TZ: Asia/Shanghai 
  LSKYPRO_VER: 2.1
  REPLACE_FILE: Services/ImageService.php

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Space cleanup and Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt update
          sudo -E apt -y full-upgrade
          sudo -E apt -y install libfuse-dev ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E systemctl daemon-reload
          sudo -E apt -y autoremove --purge
          sudo -E apt clean
          sudo -E timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download and Unzip Upstream Source Code
        working-directory: /workdir
        run: |
          df -hT $PWD
          curl -o lsky-pro https://github.com/lsky-org/lsky-pro/archive/refs/heads/master.zip
          unzip *.zip
          mv ./lsky-pro-master/* ./
          mv ./lsky-pro-master/.env.example ./
          rm -rf master.zip lsky-pro-master
          ln -sf /workdir/lsky-pro $GITHUB_WORKSPACE/lsky-pro
         
      - name: Replace ImageService.php
        run: |
          [ -e files ] && mv files lsky-pro/files
          [ -e $REPLACE_FILE ] && mv $REPLACE_FILE lsky-pro/app/Services/.config

      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
        
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
      - name: Install Dependencies
        run: composer install

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push
        run: |
          docker build -t CL/lskypro-docker:latest .
          docker push CL/lskypro-docker:latest
